name: MegaLinter

on:
  push:
    branches: [develop-17, main-17]
  pull_request:
    branches: [develop-17, main-17]

jobs:
  megalinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run MegaLinter
        uses: oxsecurity/megalinter/flavors/cupcake@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
